#!/bin/sh

aclocal_includes=""
automake_options="--add-missing --copy --gnu"

add_aclocal_prefix()
{
    if [ -d "$1/share/aclocal" ]; then
	aclocal_includes="$aclocal_includes -I $1/share/aclocal"
    fi
}

# some OSX hacks
# NOTE: this doesn't work configure.in was changed and aclocal is run
#       implicitly. bootstrap has to be run again in this case.
case `uname -s` in
    Darwin|darwin*)
	add_aclocal_prefix /usr/local	# local
	add_aclocal_prefix /sw		# fink
	add_aclocal_prefix /opt/local	# darwinports
	;;
esac

set -x
aclocal $aclocal_includes \
&& autoheader \
&& automake $automake_options \
&& autoconf

# EOF
